### ISSUE TITLE
Dropdown/auto-complete doesn't show in bootstrap modal. It shows outside of modal. 

### ISSUE THREAD

**Issue by mmswi** [kuhnza/angular-google-places-autocomplete#34]
Tried to put a z-index of 100000 to .pac-container, tried different displays, but noting...

**Comment by papasax** [comment]
Did you find a workaround?

**Comment by mmswi** [comment]
Well, we needed the modal not to close on click outside it, so first we put data-backdrop="static"; This made the modal hide the .pac-container. The way to solve it was to change the data-backdrop to "false".

**Comment by bobbyziom** [comment]
```css
div.pac-container {
	position: absolute;
	z-index: 10000;
}
```
Fixed it for me
